import numpy as np
from scipy.sparse import (csc_array, csr_array, lil_array, diags_array, kron,
                          eye_array)
import plodwave
# type hinting
from numpy.typing import NDArray


# ======================================================================
# Construction of the dg Prolongation matrix
# ======================================================================


def dg_prolongation(nelems_coarse: NDArray,
                    nelems_refine: NDArray) -> csc_array:
    """ Returns the prolongation matrix between dg meshes.

    Parameters
    ----------
    nelems_coarse : NDArray
        Number of coarse elements per dimension.
    nelems_refine : NDArray
        Number of fine elements per coarse element per dimension.

    Returns
    -------
    csc_array
        dg prolongation matrix.
    """
    d = np.size(nelems_coarse)
    dx = np.linspace(0, 1, nelems_refine[0]+1, dtype=plodwave.config.PRECISION)
    if d == 1:
        L = nelems_refine[0]*np.arange(nelems_coarse[0])[:, None]
        Q = np.arange(nelems_refine[0])
        D = _loc_prolongation(dx, dx, d)
    elif d == 2:
        # bottom left corners
        L = nelems_refine[0]*np.arange(nelems_coarse[0])\
            + (nelems_coarse[0]*np.prod(nelems_refine)
               * np.arange(nelems_coarse[1])[:, None])
        # local fine element numbering per coarse element
        Q = np.arange(nelems_refine[0])\
            + (nelems_coarse[0]
               * nelems_refine[0]*np.arange(nelems_refine[1])[:, None])
        dy = np.linspace(0, 1, nelems_refine[1]+1,
                         dtype=plodwave.config.PRECISION)[:, None]
        D = _loc_prolongation(dx, dy, d).reshape(2**d, 2**d, -1)
    # J = (Number Coarse Elements, Number Fine Elements per Coarse
    # Element, local number of DoFs)
    J = 2**d*(L.flatten()[:, None] + Q.flatten())[..., None] + np.arange(2**d)
    # K = (Number Coarse Elements, local number of DoFs)
    K = 2**d*np.arange(np.prod(nelems_coarse))[..., None] + np.arange(2**d)
    J = np.broadcast_to(J[:, None, ...],
                        (np.prod(nelems_coarse), 2**d,
                         np.prod(nelems_refine), 2**d))
    K = np.broadcast_to(K[..., None, None],
                        (np.prod(nelems_coarse), 2**d,
                         np.prod(nelems_refine), 2**d))
    D = np.broadcast_to(np.transpose(D, (0, 2, 1)),
                        (np.prod(nelems_coarse), 2**d,
                         np.prod(nelems_refine), 2**d))
    return csc_array((D.flatten(), (J.flatten(), K.flatten())))


def _loc_prolongation(interpolate_x: NDArray,
                      interpolate_y: NDArray,
                      d: int) -> NDArray:
    """ Returns the values for the local prolongation per coarse
    element.

    Parameters
    ----------
    interpolate_x : NDArray
        Values of the prolongation in x-direction.
    interpolate_y : NDArray
        Values of the prolongation in y-direction.
    d : int
        Dimension.

    Returns
    -------
    NDArray
        Local prolongation matrix per coarse element.
    """
    D = np.array([np.array([_slice(_phi(interpolate_x, interpolate_y, k, d),
                                   j, d) for j in range(2**d)],
                           dtype=plodwave.config.PRECISION)
                  for k in range(2**d)], dtype=plodwave.config.PRECISION)
    return D


def _phi(x: NDArray,
         y: NDArray,
         key: int,
         d: int) -> NDArray:
    """ Returns the values of the prolongation for the coarse nodes
    indexed with "key".

    Parameters
    ----------
    interpolate_x : NDArray
        Values of the prolongation in x-direction.
    interpolate_y : NDArray
        Values of the prolongation in y-direction.
    key : int
        Key indicating the corners of the coarse element
        3---2
        |   |
        0---1 -> d=1
    d : int
        Dimension.

    Returns
    -------
    NDArray
        Values of the prolongation per coarse node.
    """
    if d == 1:
        if key == 0:  # left corner
            return 1 - x
        if key == 1:  # right corner
            return x
    elif d == 2:
        if key == 0:  # bottom left corner
            return (1 - x) * (1 - y)
        if key == 1:  # bottom right corner
            return x * (1 - y)
        if key == 2:  # top right corner
            return x * y
        if key == 3:  # top left corner
            return (1 - x) * y


def _slice(phi: NDArray,
           key: int,
           d: int) -> NDArray:
    """ Uses the values generated by _phi and returns the correct values
    for the local nodes indicated by "key" for the fine elements.

    Parameters
    ----------
    phi : NDArray
        Values of the prolongation per coarse node constructed by _phi.
    key : int
        Key indicating the corners of the coarse element
        3---2
        |   |
        0---1 -> d=1
    d : int
        Dimension.

    Returns
    -------
    NDArray
        Values of the prolongation per coarse node constructed by _phi
        for the fine ndoes indicate by "key".
    """
    if d == 1:
        if key == 0:  # left corner
            return phi[:-1]
        if key == 1:  # right corner
            return phi[1:]
    elif d == 2:
        if key == 0:  # bottom left corner
            return phi[:-1, :-1]
        if key == 1:  # bottom right corner
            return phi[:-1, 1:]
        if key == 2:  # top right corner
            return phi[1:, 1:]
        if key == 3:  # top left corner
            return phi[1:, :-1]


def cg_prolongation(nelems_coarse: NDArray,
                    nelems_refine: NDArray) -> csc_array:
    """ Returns the cg prolongation matrix.

    Parameters
    ----------
    nelems_coarse : NDArray
        Number of coarse elements per dimension.
    nelems_refine : NDArray
        Number of fine elements per dimension per coarse element.

    Returns
    -------
    csc_array
        cg prolongation matrix.
    """
    d = np.size(nelems_coarse)
    dx = np.linspace(1, 0, nelems_refine[0]+1,
                     dtype=plodwave.config.PRECISION)[:-1]
    if d == 1:
        L = np.arange(nelems_coarse[0], dtype=np.int32)
        J = (nelems_refine[0]*np.arange(nelems_coarse[0], dtype=np.int32)
             + np.arange(2, dtype=np.int32)[:, None]).flatten()
        J = (J[:, None] + np.arange(nelems_refine[0], dtype=np.int32)).flatten()
        K = (L+np.array([[0], [1]])).flatten()
        K = np.repeat(K, nelems_refine[0])
        D = np.tile(dx, (nelems_coarse[0],))
        D = np.concatenate([D, D[::-1]])
        P = lil_array((np.prod(nelems_coarse*nelems_refine+1),
                       np.prod(nelems_coarse+1)))
        P[J, K] = D
    elif d == 2:
        J = ((nelems_refine[0]*np.arange(nelems_coarse[0], dtype=np.int32)
             + ((nelems_coarse[0]*nelems_refine[0]+1)*nelems_refine[1]
                * np.arange(nelems_coarse[1], dtype=np.int32)[:, None])
              )[:, None, :, None]
             + np.arange(nelems_refine[0], dtype=np.int32)
             + ((nelems_refine[0]*nelems_coarse[0]+1)
                * np.arange(nelems_refine[1], dtype=np.int32))[:, None, None]
             ).reshape((nelems_coarse*nelems_refine)[::-1])
        J = (J
             + np.array([0, 1, (nelems_coarse[0]*nelems_refine[0]+1)+1,
                         (nelems_coarse[0]*nelems_refine[0]+1)],
                        dtype=np.int32)[:, None, None]).flatten()
        K = (np.arange(nelems_coarse[0], dtype=np.int32)
             + (nelems_coarse[0]+1)*np.arange(nelems_coarse[1],
                                              dtype=np.int32)[:, None])
        K = (np.repeat(np.repeat(K, nelems_refine[0], axis=1),
                       nelems_refine[1], axis=0)
             + np.array([0, 1, nelems_coarse[0]+2, nelems_coarse[0]+1],
                        dtype=np.int32)[:, None, None]).flatten()
        dy = np.linspace(1, 0, nelems_refine[1]+1,
                         dtype=plodwave.config.PRECISION)[:-1]
        D = np.tile(np.outer(dy, dx), nelems_coarse[::-1])
        D = np.concatenate([D.flatten(),
                            D[:, ::-1].flatten(),
                            D[::-1, ::-1].flatten(),
                            D[::-1, :].flatten()])
        P = lil_array((np.prod(nelems_coarse*nelems_refine+1),
                       np.prod(nelems_coarse+1)))
        P[J, K] = D
    return csc_array(P)


def element_prolongation(nelems_coarse: NDArray,
                         nelems_refine: NDArray) -> csr_array:
    """ Returns a prolongation array based on coarse to fine elements.

    Parameters
    ----------
    nelems_coarse : NDArray
        Number of coarse elements per dimension.
    nelems_refine : NDArray
        Number of fine elements per dimension per coarse element.

    Returns
    -------
    csc_array
        Element-wise prolongation matrix.
    """
    d = np.size(nelems_coarse)
    J = np.arange(np.prod(nelems_coarse*nelems_refine), dtype=np.int32)
    if d == 1:
        K = np.arange(np.prod(nelems_coarse), dtype=np.int32)
        K = np.repeat(K, nelems_refine[0])
        return csr_array((np.ones_like(J, dtype=plodwave.config.PRECISION),
                          (J, K)))
    K = np.arange(np.prod(nelems_coarse),
                  dtype=np.int32).reshape(nelems_coarse, order='F')
    K = np.repeat(np.tile(K, (nelems_refine[1], 1)), nelems_refine[0],
                  axis=0).flatten('F')
    return csr_array((np.ones_like(J, dtype=plodwave.config.PRECISION),
                      (J, K)))


def cg_dof_projection(dofs: NDArray,
                      nelems: NDArray) -> csc_array:
    """ Returns restriction to DoFs as csc array.

    Parameters
    ----------
    dofs : NDArray
        DoFs.
    nelems : NDArray
        Number of elements per dimension.

    Returns
    -------
    csc_array
        DoF restrictions map.
    """
    N = np.size(dofs)
    return csc_array((np.ones_like(dofs), (dofs, np.arange(N))),
                     shape=(np.prod(nelems+1), N))


# ======================================================================
# Construction of the cg2dg matrix
# ======================================================================


def get_cg2dg(elements: NDArray) -> csc_array:
    """ Returns the cg to dg matrix.

    Parameters
    ----------
    elements : NDArray
        Element array.

    Returns
    -------
    csc_array
        cg to dg matrix.
    """
    return csc_array((np.ones((np.size(elements),),
                              dtype=plodwave.config.PRECISION),
                      (np.arange(np.size(elements), dtype=np.int32),
                       elements.flatten())))


def get_cg2dg_coarse_fine(nelems_coarse: NDArray,
                          nelems_refine: NDArray) -> csc_array:
    """ Returns coarse cg to dg map interpolated in fine nodes.

    Parameters
    ----------
    nelems_coarse : NDArray
        Number of coarse elements per dimension.
    nelems_refine : NDArray
        Number of fine elements per dimension per coarse element.

    Returns
    -------
    csc_array
        Coarse cg to dg map interpolated in fine nodes.
    """
    d = np.size(nelems_coarse)
    nelems_fine = nelems_coarse * nelems_refine
    J = np.arange(np.prod(nelems_coarse*(nelems_refine+1)),
                  dtype=np.int32)
    if d == 1:
        K = np.arange(nelems_refine[0]+1)\
            + nelems_refine[0]*np.arange(nelems_coarse[0])[:, None]
    elif d == 2:
        K = np.arange(nelems_refine[0]+1)\
            + (nelems_fine[0]+1)\
            * np.arange(nelems_refine[1]+1)[:, None]
        K = K.flatten()\
            + (nelems_refine[0]*np.arange(nelems_coarse[0])
               + nelems_refine[1]*(nelems_fine[0]+1)
               * np.arange(nelems_coarse[1])[:, None]).reshape(-1, 1)
    return csc_array((np.ones_like(J), (J, K.flatten())))


def get_cg2dg0(nelems: NDArray, cg2dg: csc_array) -> csr_array:
    """ Returns the cg (p=1) to dg (p=0) matrix.

    Parameters
    ----------
    nelems : NDArray
        Number of elements per dimension.
    cg2dg : csc_array
        Oridnary cg to dg map.

    Returns
    -------
    csr_array
        cg (p=1) to dg (p=0) matrix.
    """
    d = np.size(nelems)
    return kron(eye_array(np.prod(nelems)), np.ones((1, 2**d))/(2**d),
                format='csr').dot(cg2dg)


def averaging(cg2dg: csc_array) -> csc_array:
    """ cg to dg map with averaging on a patch.

    Parameters
    ----------
    Elements : NDArray
        Element array.
    PatchIndices : NDArray
        Node indices within the patch.
    cg2dg : csc_array
        cg to dg map on the patch.

    Returns
    -------
    csc_array
        cg to dg averaging map on a patch.
    """
    C = csc_array(cg2dg.T)
    # We compute the number of elements around the patch nodes to mimic
    # the global averaging operator restricted to the patch.
    N = np.sum(C.toarray(), axis=1, dtype=plodwave.config.PRECISION)
    return csc_array(diags_array(1/N) @ C)


# ======================================================================
# Definition of the local stiffness and mass matrices
# ======================================================================


def loc_stiffness(nelems: NDArray,
                  domain: NDArray) -> NDArray:
    """ Returns the local stiffness matrix on one element.

    Parameters
    ----------
    nelems : NDArray
        Number of elements per dimension.
    domain : NDArray
        Array with the domain boundary values.

    Returns
    -------
    NDArray
        Local stiffness matrix on one element.
    """
    d = np.size(nelems)
    B = (domain[1, :] - domain[0, :])/nelems
    if d == 1:
        S = np.array([[1, -1],
                      [-1, 1]], dtype=plodwave.config.PRECISION)/B[0]
    elif d == 2:
        # integral of first component of the gradient:
        S = np.array([[2, -2, -1, 1],
                      [-2, 2, 1, -1],
                      [-1, 1, 2, -2],
                      [1, -1, -2, 2]],
                     dtype=plodwave.config.PRECISION)/6/(B[0]**2)
        # integral of second component of the gradient:
        S += np.array([[2, 1, -1, -2],
                       [1, 2, -2, -1],
                       [-1, -2, 2, 1],
                       [-2, -1, 1, 2]],
                      dtype=plodwave.config.PRECISION)/6/(B[1]**2)
        S *= np.prod(B)  # = det B
    return S


def loc_mass(nelems: NDArray,
             domain: NDArray) -> NDArray:
    """ Returns the local mass matrix on one element.

    Parameters
    ----------
    nelems : NDArray
        Number of elements per dimension.
    domain : NDArray
        Array with the domain boundary values.

    Returns
    -------
    NDArray
        Local mass matrix on one element.
    """
    d = np.size(nelems)
    if d == 1:
        M = np.array([[2, 1],
                      [1, 2]], dtype=plodwave.config.PRECISION)/6
    elif d == 2:
        M = np.array([[4, 2, 1, 2],
                      [2, 4, 2, 1],
                      [1, 2, 4, 2],
                      [2, 1, 2, 4]], dtype=plodwave.config.PRECISION)/36
    return np.prod((domain[1, :] - domain[0, :])/nelems) * M


def loc_mass_inv(nelems: NDArray,
                 domain: NDArray) -> NDArray:
    """ Returns the local inverse mass matrix on one element.

    Parameters
    ----------
    nelems : NDArray
        Number of elements per dimension.
    domain : NDArray
        Array with the domain boundary values.

    Returns
    -------
    NDArray
        Local inverse mass matrix on one element.
    """
    d = np.size(nelems)
    if d == 1:
        M = np.array([[2, -1],
                      [-1, 2]], dtype=plodwave.config.PRECISION)*2
    elif d == 2:
        M = np.array([[4, -2, 1, -2],
                      [-2, 4, -2, 1],
                      [1, -2, 4, -2],
                      [-2, 1, -2, 4]], dtype=plodwave.config.PRECISION)*4
    return np.prod(nelems/(domain[1, :] - domain[0, :])) * M


# ======================================================================
# Assembly of the global matrices
# ======================================================================


def assemble_matrices(nelems: NDArray,
                      loc: NDArray,
                      mesh_type: str = 'dg',
                      cg2dg: csc_array | None = None,
                      weight: NDArray | None = None) -> csr_array:
    """ Returns a global cg or dg matrix based on the local matrix loc,
    with weights.

    Parameters
    ----------
    nelems : NDArray
        Number of elements per dimension.
    loc : NDArray
        Local matrix.
    mesh_type : str, optional
        Choice between 'cg' or 'dg' matrix, by default 'dg'.
    cg2dg : csc_array | None, optional
        cg to dg matrix that is needed for the cg assembly, by default
        None.
    weight : NDArray | None, optional
        Weighting the local matrices, by default None which represents
        constant 1 coefficient.

    Returns
    -------
    csr_array
        Global matrix.
    """
    if weight is None:
        weight = np.ones((np.prod(nelems),), dtype=plodwave.config.PRECISION)
    assert np.size(weight) == np.prod(nelems), 'The coefficient is not'\
        + ' properly defined for the underlying fine mesh.'
    if weight.ndim == 2:
        weight = weight.flatten()
    if mesh_type == 'dg':
        return _dg_assembly(loc, weight)
    return _cg_assembly(cg2dg, loc, weight)


def _dg_assembly(loc: NDArray,
                 weight: NDArray) -> csr_array:
    """ Assmebles the global dg matrix based on loc with weigths.

    Parameters
    ----------
    loc : NDArray
        Local matrix.
    weight : NDArray
        Weight per element.

    Returns
    -------
    csr_array
        Global matrix.
    """
    return csr_array(kron(diags_array(weight), loc))


def _cg_assembly(cg2dg: NDArray,
                 loc: NDArray,
                 weight: NDArray) -> csr_array:
    """ Assmebles the global cg matrix based on loc with weigths.

    Parameters
    ----------
    NElems : NDArray
        Number of elements per dimension.
    loc : NDArray
        Local matrix.
    weight : NDArray
        Weight per element.

    Returns
    -------
    csr_array
        Global matrix.
    """
    dg_matrix = _dg_assembly(loc, weight)
    return csr_array(cg2dg.T @ (dg_matrix @ cg2dg))
